(source "jcs-elpa")
(source "melpa")

(package "hl-preproc" "0.1.0" "Unhighlight invalid preprocessor region")

(package-file "hl-preproc.el")

(depends-on "emacs" "24.5")
(depends-on "meta-net")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn t)
